/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from './stencil.core';


export namespace Components {
  interface NovaBadge {
    /**
    * The score
    */
    'score': string;
  }
}

declare global {


  interface HTMLNovaBadgeElement extends Components.NovaBadge, HTMLStencilElement {}
  var HTMLNovaBadgeElement: {
    prototype: HTMLNovaBadgeElement;
    new (): HTMLNovaBadgeElement;
  };
  interface HTMLElementTagNameMap {
    'nova-badge': HTMLNovaBadgeElement;
  }
}

declare namespace LocalJSX {
  interface NovaBadge extends JSXBase.HTMLAttributes<HTMLNovaBadgeElement> {
    /**
    * The score
    */
    'score'?: string;
  }

  interface IntrinsicElements {
    'nova-badge': NovaBadge;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


